import { Download, Ellipsis, Eye, ArrowUpRight } from 'lucide-react'
import StatusBadge from './StatusBadge'

type CertificateStatus = 'Valid' | 'Expired' | 'Revoked'
type CertificateRow = [string, string, string, string, string, string, CertificateStatus]
const certificates: CertificateRow[] = [['CERT-2026-0001248', 'Lim Potkolbotey', 'lim@example.com', 'Blockchain Development', 'May 23, 2026', 'May 23, 2027', 'Valid'], ['CERT-2026-0001247', 'Sokha Ngin', 'sokha@example.com', 'Smart Contract Basics', 'May 22, 2026', 'May 22, 2027', 'Valid'], ['CERT-2026-0001246', 'Dara Vimean', 'dara@example.com', 'Web3 Fundamentals', 'May 21, 2026', 'May 21, 2026', 'Expired'], ['CERT-2026-0001245', 'Srey Mom', 'srey@example.com', 'Decentralized App (DApp)', 'May 19, 2026', 'May 19, 2027', 'Revoked'], ['CERT-2026-0001244', 'Vannak Keo', 'vannak@example.com', 'Ethereum Development', 'May 18, 2026', 'May 18, 2027', 'Valid']]

function RecentCertificates() { return <section className="recent-certificates dashboard-card dashboard-enter"><div className="card-heading"><div><h2>Recent Certificates</h2><p>The latest credentials issued by your organization.</p></div><a href="#coming-soon">View all certificates <ArrowUpRight size={16} /></a></div><div className="table-wrap"><table><thead><tr><th>Certificate ID</th><th>Recipient</th><th>Course / Program</th><th>Issue Date</th><th>Expiration Date</th><th>Status</th><th aria-label="Actions" /></tr></thead><tbody>{certificates.map(([id, name, email, course, issued, expiration, status]) => <tr key={id}><td><code>{id}</code></td><td><b>{name}</b><small>{email}</small></td><td>{course}</td><td>{issued}</td><td>{expiration}</td><td><StatusBadge status={status} /></td><td><div className="table-actions"><button title="View certificate"><Eye size={16} /></button><button title="Download certificate"><Download size={16} /></button><button title="More actions"><Ellipsis size={17} /></button></div></td></tr>)}</tbody></table></div></section> }
export default RecentCertificates
