import { ArrowLeft, ArrowRight, FileText, Save } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import DashboardLayout from '../layouts/DashboardLayout'
import CertificateStepper from '../components/certificates/CertificateStepper'
import RecipientStep from '../components/certificates/RecipientStep'
import CertificateDetailsStep from '../components/certificates/CertificateDetailsStep'
import CertificateDesignStep from '../components/certificates/CertificateDesignStep'
import ReviewCertificateStep from '../components/certificates/ReviewCertificateStep'
import IssueSuccessModal from '../components/certificates/IssueSuccessModal'
import type { CertificateFormData } from '../types/certificate'

const initialForm: CertificateFormData = { recipient: { name: '', email: '', recipientId: '', organization: '' }, certificateTitle: '', program: '', description: '', issueDate: '2026-08-20', hasExpiration: false, expirationDate: '', achievement: '', template: 'classic', organizationName: 'Kirirom Institute of Technology', signerName: '', signerTitle: '', accent: 'blue' }
export default function CreateCertificate() { const [step, setStep] = useState(0); const [form, setForm] = useState(initialForm); const [errors, setErrors] = useState<Record<string, string>>({}); const [issued, setIssued] = useState(false); const change = (field: string, value: string | boolean) => { if (field in form.recipient) setForm(f => ({ ...f, recipient: { ...f.recipient, [field]: value } })); else setForm(f => ({ ...f, [field]: value })); setErrors(e => ({ ...e, [field]: '' })) }; const validate = () => { const next: Record<string, string> = {}; if (step === 0) { if (!form.recipient.name.trim()) next.name = 'Recipient name is required.'; if (!/^\S+@\S+\.\S+$/.test(form.recipient.email)) next.email = 'Enter a valid email address.' } if (step === 1) { if (!form.certificateTitle.trim()) next.certificateTitle = 'Certificate title is required.'; if (!form.program.trim()) next.program = 'Program is required.'; if (!form.issueDate) next.issueDate = 'Issue date is required.' } setErrors(next); return !Object.keys(next).length }; const next = () => { if (validate()) setStep(s => Math.min(3, s + 1)) }; const startOver = () => { setForm(initialForm); setStep(0); setIssued(false) }; return <DashboardLayout><div className="dashboard-content certificate-content"><div className="certificate-page-heading"><div><nav>Certificates <span>/</span> Issue Certificate</nav><h1>Issue a New Certificate</h1><p>Create a secure digital credential for your recipient.</p></div><span className="draft-status"><i /> Draft</span></div><div className="certificate-workspace dashboard-enter"><CertificateStepper current={step} /><div className="certificate-panel">{step === 0 && <RecipientStep form={form} errors={errors} onChange={change} />}{step === 1 && <CertificateDetailsStep form={form} errors={errors} onChange={change} />}{step === 2 && <CertificateDesignStep form={form} onChange={change} />}{step === 3 && <ReviewCertificateStep form={form} />}</div><footer className="certificate-actions">            {step === 0 ? <Link to="/dashboard" className="cancel-action">Cancel</Link> : <button className="cancel-action" onClick={() => setStep(s => s - 1)}><ArrowLeft size={16} /> Back</button>}<div>{step === 3 && <button className="save-draft"><Save size={15} /> Save as Draft</button>}{step < 3 ? <button className="issue-action" onClick={next}>Continue <ArrowRight size={16} /></button> : <button className="issue-action" onClick={() => setIssued(true)}><FileText size={16} /> Issue Certificate</button>}</div></footer>          </div></div>{issued && <IssueSuccessModal onClose={() => setIssued(false)} onAnother={startOver} />}</DashboardLayout> }
